### ISSUE TITLE
Reload is not triggered when watching multiple volume dirs

### ISSUE THREAD

**Issue by dannyk81** [jimmidyson/configmap-reload#6]
I'm setting configmap-reload in the same Pod as Prometheus to monitor two directories :

```
      - name: configmap-reload
        image: docker.tuenti.io/monitoring/configmap-reload:v0.1
        args:
          - --volume-dir=/etc/prometheus/config
          - --volume-dir=/etc/prometheus/rules
          - --webhook-url=http://localhost:9090/-/reload
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/config
          readOnly: true
        - name: rules-volume
          mountPath: /etc/prometheus/rules
          readOnly: true
```

Changing the config files in any of these volume dirs doesn't trigger a reload, if I keep just one of them - it works.

Am I missing something? any ideas?

Thanks!
